apiVersion: v1
kind: Pod
metadata:
  name: my-label-pod
  labels:
    name: frontend
    environment: dev
    project: roboshop
    version: "1.0"
spec:
  containers:
    - name: frontend
      image: nginx