apiVersion: v1
kind: Pod
metadata:
  name: pod-configmap
spec:
  containers:
  - name: nginx-container
    image: nginx
    envFrom:
    - configMapRef:
        name: configmap


## This pod is using a ConfigMap named "configmap" to set environment variables for the nginx container.
## The ConfigMap contains key-value pairs that can be used to configure the application running in the container.