apiVersion: v1
kind: Secret
metadata:
  name: secret-config
type: Opaque 

data:
  User: "QWRtaW4K"
  Password: "cGFzc3dvcmQK"

## use of Opaque type in Kubernetes secrets allows you to store arbitrary data in key-value pairs, where the values are base64-encoded strings. 
## This type is commonly used for storing sensitive information such as passwords, API keys, or any other confidential data that you want to keep secure within your Kubernetes cluster.  