apiVersion: v1
kind: Service
metadata:
  name: nginx-service-lb
spec: 
  type: loadBalancer
  selectors:
    project: JCS-Global-service
    user: maruthi
    role: project-lead
    purpose: load-balancer
  ports:  
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30070

## This is used to specify the port on which the service is exposed to the outside world,
## so that we can access the service from outside of the cluster using this port
