apiVersion: v1
kind: Service
metadata:
  name: nginx-service-lb
spec: 
  type: loadBalancer
  selectors:
    project: JCS-Global-service
    user: maruthi
    role: project-lead
    purpose: load-balancer
  ports:  
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30070