apiVersion: v1
kind: Pod
metadata:
  name: lb-pod
  labels:
    project: JCS-Global-service
    user: maruthi
    role: project-lead
    purpose: load-balancer
spec:
  containers:
    - name: nginx-container
      image: nginx
