apiVersion: v1
kind: Pod
metadata:
  name: lb-pod
  labels:
    project: JCS-Global-service
    user: maruthi
    role: project-lead
    purpose: load-balancer
spec:
  containers:
    - name: nginx-container
      image: nginx


## the labels specified in the pod are used to select the pods for the service, 
## so that the service can route the traffic to the selected pods.