apiVersion: v1
kind: Pod
metadata:
  name: resource-pod
spec:
  containers:
    - name: resource-container
      image: nginx
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
        requests:
          memory: "64Mi"
          cpu: "250m"

### This file container is used to create a pod with resource limits and requests.
## The container will be limited to using 128Mi of memory and 500m of CPU, 
## because container does not have miss use resources, so we are giving it some resource limits.