FROM almalinux:9
ADD https://github.com/Maruthi22k/PythonRepo/blob/main/.github/workflows/main.yml /tmp/note.txt
## RUN cat /tmp/note.txt

## option two this one is for local file
ADD tar_file.tar.gz /tmp/

CMD ["sleep", "100"]