apiVersion: v1
kind: Pod
metadata:
  name: rbac-test
  namespace: dev-env
spec:
  serviceAccountName: dev-user
  containers:
  - name: nginx
    image: nginx:alpine


# kubectl apply -f pod.yaml
# kubectl get pod -n dev-env
# kubectl get pod rbac-test -n dev-env -o jsonpath='{.spec.serviceAccountName}'