

apiVersion: v1
kind: ServiceAccount
metadata:
  name: dev-user
  namespace: dev-env


# kubectl create namespace dev-env
# kubectl apply -f serviceAccount.yaml
#kubectl get serviceAccount -n dev-env