- name: varible declaration in playbook inventory variables 
  hosts: local
  connection: local
  
  tasks:
    - name: Print varibles
      ansible.builtin.debug:
        msg: "this is the ansible facts: {{ COURSE_NAME }}"
