- name: Condition check inAnsible
  hosts: local
  connection: local
  vars:
    IS_LIVE: true

  tasks:
    - name: check the condition
      ansible.builtin.debug:
        msg: "this is live condsitions check"
      when: IS_LIVE == true


## Command-- ansible-playbook -i inventory.ini 08-conditionCheck.yaml