- name: Condition chec ansible_facts
  hosts: local
  connection: local
  tasks:
    - name: get data from using ansible_facts
      ansible.builtin.debug:
        msg: "full data == {{ansible_facts}}" 
       ## msg: "The OS is {{ ansible_distribution }} and the version is {{ ansible_distribution_version }}"