- name: set fact varibles
  hosts: all
  connection: local

  tasks:
    - name: Set a fact
      set_fact:
        app_name: "payment-service"
        msg: "This is a message"
   # - debug:
   #     msg: "Application name is {{ app_name }} and message is {{ msg }}"
