- name: loop Condition files
  hosts: local
  connection: local

  tasks:
    - name: name mysql project
      ansible.builtin.debug:
        msg: "this value {{NAME}}"

      loop:
       - Maruthirao
       - Anusha
       - SaiSidvik
       - Sridhartri



  #  - name:     