- name: Loop names 
  hosts: local
  connection: local
  tasks: 
    - name: Loopin values
      ansible.builtin.debug:
#        msg: " this is value {{NAME}}"
        msg: " this is value {{item}}"
      loop: 
      - maruthiraok
      - Anusha
      - SaiSidvik
      - Sridhatri