- name: filter values in ansible
  hosts: local
  connection: local

  tasks:
    - name: filter values in ansible
      ansible.builtin.debug:
        msg: "this maruthirao is {{ GREETINGS | default('welcome Maruthiraok')}}"
        msg: "this maruthirao is {{ GREETINGS | default(5)}}"
