apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::495209412092:role/eksctl-roboshop-dev-nodegroup-robo-NodeInstanceRole-lZ2mDTBErpS2
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - roboshop-trainee
      userarm: arn:aws:iam::495209412092:user/Maruthi   ## IAMuser 
      username: Maruthi

    - groups:
      - roboshop-admin
      userarm: arn:aws:iam::495209412092:user/TF-IAM
      username: TF-IAM

kind: ConfigMap
metadata:
  creationTimestamp: "2026-09-28T10:59:13Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1203"
  uid: 2fa89f58-93a3-4632-98e3-f371d878c7f1


## kubectl get configmap aws-auth -n kube-system -o yaml

# summary two users created one is TF-IAM "lead or admin" all access
# next user maruthi so just read only access not write access
