
apiVersion: rbac.authorization.k8s.io/v1
kind: Role

metadata:
  name: roboshop-trinee
  namespace: roboshop

rules:
  - apiGroups: [""]     # incedent core api group like replica, service , pod, those are core other base also
    resources: ["pods"]
    verbs: ["get", "list", "watch"]


  # kubectl get configmap aws-auth -n kube-system -o yaml

